window.QUESTIONNAIRE_RESULTS_API_URL = "";
window.QUESTIONNAIRE_GITHUB_OWNER = "itcohesion";
window.QUESTIONNAIRE_GITHUB_REPO = "answers";
window.QUESTIONNAIRE_GITHUB_BRANCH = "main";
window.QUESTIONNAIRE_GITHUB_TOKEN = "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";
window.QUESTIONNAIRE_GITHUB_PATH_PREFIX = "responses";
