window.QUESTIONNAIRE_RESULTS_API_URL = "";
window.QUESTIONNAIRE_GITHUB_OWNER = "itcohesion";
window.QUESTIONNAIRE_GITHUB_REPO = "answers";
window.QUESTIONNAIRE_GITHUB_ISSUE_LABEL = "questionnaire-response";
window.QUESTIONNAIRE_GITHUB_ISSUE_URL = "";
