window.QUESTIONNAIRE_RESULTS_API_URL = "";
window.QUESTIONNAIRE_GITHUB_OWNER = "itcohesion";
window.QUESTIONNAIRE_GITHUB_REPO = "answers";
window.QUESTIONNAIRE_GITHUB_BRANCH = "main";
window.QUESTIONNAIRE_GITHUB_TOKEN = "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";
window.QUESTIONNAIRE_GITHUB_PATH_PREFIX = "responses";
